BuildPath = "cmd/ares/main.go"

defaultDeployment = "explorer"

[deployments]
    [deployments.nfc]
        hosts = ["pi@pi-4.local"]
        paths = [
            "./nfc/:~/go/src/bitbucket.org/unchain-bc1718/medchain/nfc/"
        ]
        
        remoteCommand = """
            cd ~/go/src/bitbucket.org/unchain-bc1718/medchain/nfc/
            /usr/local/go/bin/go run cmd/nfc/main.go
        """

    [deployments.mac]
        hosts = ["pi@pi-4.local"]

        paths = [
            "bin/mac:~/mac",
            "nfc/config/$HOST/"
        ]
        
        localCommand = """
            export GOARCH="arm"
            export GOOS="linux"
            GOARM=7
             
            go build -o bin/mac nfc/cmd/mac/main.go
        """

        remoteCommand = """
            ./mac
        """

    [deployments.janus]
        hosts = ["pi@pi-1.local", "pi@pi-2.local", "pi@pi-3.local", "pi@pi-4.local"]

        paths = [
            "janus/:~/janus/"
        ]

        remoteCommand = """
            cd ~/janus
            docker-compose pull janus
            docker-compose up --force-recreate -d
        """

    [deployments.explorer]
        hosts = ["pi@pi-commander-01"]

        paths = [
            "blockchain-explorer/:~/blockchain-explorer/"
        ]

        remoteCommand = """
            cd ~/blockchain-explorer
            docker-compose pull blockchain-explorer
            docker-compose up --force-recreate -d
        """

    [deployments.chaincode]
        hosts = ["core@37.139.12.130"]

        paths = [
            "chain-code/:~/blockchaingers18/"
        ]

        remoteCommand = """
            cd ~/chain-code
            docker-compose up --force-recreate -d
        """
