# https://github.com/yeasy/docker-compose-files/tree/master/hyperledger
# This compose file will start a Hyperledger Fabric 1.0 MVE, including
# * 2 ca (not in use now)
# * 1 orderer
# * 4 peers in 2 orgs
# * cli for testing
# * blockchain-explorer

version: '2.0'

services:
# ca.org1.example.com:
#   extends:
#     file: base-solo.yaml
#     service: ca.org1.example.com

# ca.org2.example.com:
#   extends:
#     file: base-solo.yaml
#     service: ca.org2.example.com

  cli:
    extends:
      file: base-solo.yaml
      service: cli

  orderer.example.com:  # There  can be multiple orderers
    extends:
      file: base-solo.yaml
      service: orderer.example.com

  peer0.org1.example.com:
    extends:
      file: base-solo.yaml
      service: peer0.org1.example.com

  peer1.org1.example.com:
    extends:
      file: base-solo.yaml
      service: peer1.org1.example.com

  peer0.org2.example.com:
    extends:
      file: base-solo.yaml
      service: peer0.org2.example.com

  peer1.org2.example.com:
    extends:
      file: base-solo.yaml
      service: peer1.org2.example.com

  explorer:
    extends:
      file: base.yaml
      service: explorer-base
    container_name: explorer
    hostname: explorer
    depends_on:
      - mysql
    volumes:
      - ./explorer-artifacts/config.json:/blockchain-explorer/config.json
      - ./crypto-config:/blockchain-explorer/first-network/crypto-config
    ports:
      - "8080:8080"  # HTTP port

  mysql: # mysql service
    extends:
      file: base.yaml
      service: mysql-base
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fabricexplorer
    volumes:
      - ./explorer-artifacts/fabricexplorer.sql:/docker-entrypoint-initdb.d/fabricexplorer.sql
    #command: bash -c 'mysqld; sleep 1; mysql -uroot -proot < /tmp/fabricexplorer.sql; while true; do sleep 20171117; done'

#networks:
#  default:
#    external:
#      name: hyperledger_fabric
