
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/hyperledger/fabric"
  version = "1.1.0-preview"

[[constraint]]
#  branch = "master"
  revision = "614551a752802488988921a730b172dada7def1d"
  name = "github.com/hyperledger/fabric-sdk-go"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"
